apiVersion: apps/v1
kind: Deployment
metadata:
  name: got-em-recruiters
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: got-em-recruiters
  template:
    metadata:
      labels:
        app: got-em-recruiters
    spec:
      containers:
        - name: got-em-recruiters
          image: got-em-recruiters:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: got-em-recruiters-balancer
spec:
  selector:
    app: got-em-recruiters
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
